version: '3.7'

services:

  node-app:
    build: .
    image: node-app:1.0
    ports:
      - '9999:9999'

  PostgreSQL:

    image: postgres:12-alpine
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_DB=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=pass

  mySQL:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      - MYSQL_DB=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=pass